added __init__.py for package structure
(base) PS D:\churn prediction> git pull origin main --rebase
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 4.35 KiB | 44.00 KiB/s, done.
From https://github.com/PandeyPranjal/customer-churn-prediction-fastapi
 * branch            main       -> FETCH_HEAD
   4c84cf1..653a2ab  main       -> origin/main
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
error: could not apply 98c9b9e... added __init__.py for package structure
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 98c9b9e... # added __init__.py for package structure
(base) PS D:\churn prediction> git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

(base) PS D:\churn prediction> #